version: "3.8"

services:
  db_service:
    image: mysql:8.0
    container_name: db_TIM_B1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: absensi_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - absensi_net

  app_service:
    build: ./app
    container_name: app_TIM_B1
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db_service
    networks:
      - absensi_net

  nginx_service:
    image: nginx:alpine
    container_name: nginx_TIM_B1
    ports:
      - "2562:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - absensi_net


volumes:
  db_data:

networks:
  absensi_net:
    driver: bridge


